#include "dialog.h"
#include "./ui_dialog.h"
#include <QDir>

Dialog::Dialog(QWidget *parent)
    : QDialog(parent)
    , ui(new Ui::Dialog)
{
    ui->setupUi(this);
    configureLocations();
    readJson();
//    connect(ui->ksShortcut, &QKeySequenceEdit::editingFinished,this, &Dialog::saveSequence);
    QJsonArray kbdArray = kbdConfig.array();
    QStringList cmbItems;
    for(auto curr: kbdArray) {
        QJsonObject binding = curr.toObject();
        cmbItems.push_back(binding["name"].toString());
    }
    ui->cmbAction->insertItems(0,cmbItems);
    ui->cmbAction->setCurrentIndex(0);
}

Dialog::~Dialog()
{
    delete ui;
}

void Dialog::configureLocations()
{
    QProcessEnvironment env;
    QString homeDir = env.systemEnvironment().value("HOME") + '/';
    configDir = homeDir + ".config/swaykbd-settings/";
    configLoc = configDir + configFilename;
    configFile.setFileName(configLoc);
}

// Read JSON from config file
void Dialog::readJson()
{
    // Create new file using default config (default.json)
    if(!configFile.exists()) {
        qInfo() << "Couldn't find file: "<<configFile.fileName()
                << "At" << configDir;
        QDir dir(configDir);
        if(!dir.exists())
            dir.mkpath(configDir);
        resetDefaults();
    }

    // Read and parse JSON
    configFile.open(QFile::ReadOnly);
    configFile.seek(0);
    QString jsonStr= configFile.readAll();
    configFile.close();
    kbdConfig = QJsonDocument::fromJson(jsonStr.toLocal8Bit());
    if(kbdConfig.isNull())
        qCritical() << "Config File is Invalid";
    else
        qInfo() << "Successfully Parsed Config File";
}

// Convert JSON to string and write into config file
void Dialog::writeJson()
{
    QByteArray json = kbdConfig.toJson();
    writeJson(json);
}

// Write JSON string to config file
void Dialog::writeJson(QByteArray &json)
{
    if(configFile.isOpen())
        configFile.close();
    if(!configFile.open(QFile::WriteOnly))
        qCritical()<<"Failed to open file for writing. Changes may be lost.";
    configFile.seek(0);
    if(configFile.write(json) < 0) {
        qCritical() << "Failed to write into config file: "<<configFile.errorString();
    }
    configFile.close();
}

void Dialog::writeConfig(QByteArray &s)
{
    QFile gen(configDir+"kbd_config");
    gen.open(QFile::WriteOnly);
    gen.write(s);
    gen.close();
}

bool Dialog::validateConfigObject(QJsonObject &obj)
{
    if(!obj.contains("type") || !obj["type"].isString()
            || ( obj.contains("clause") && !obj["clause"].isString() )
            || ( obj.contains("combi") && !obj["combi"].isString() )
            || ( obj.contains("locked") && !obj["locked"].isBool() ))  {
        qCritical() << "Invalid JSON Format";
        return false;
    }
    return true;
}

// Reset to default configs
void Dialog::resetDefaults()
{
    QFile def("default.json");
    if(!def.exists()) {
        qCritical() << "Couldn't find/open default config file: default.json"
                << def.errorString();
        throw def.error();
    }
    if(!def.open(QFile::ReadOnly)) {
        qCritical() << "Couldn't Open";
    }
    qInfo() << "Found default config: " << def.fileName()
            << "At" << QDir::currentPath();
    def.seek(0);
    QByteArray defaultJson = def.readAll();
    def.close();
    writeJson(defaultJson);
    readJson();
    on_cmbAction_currentIndexChanged(0);
}

QByteArray Dialog::generateConfig()
{
    QJsonArray kbdBindings = kbdConfig.array();
    QByteArray configStr = "**** Generated By Sway Shortcuts Manager ****\n\n";
    foreach(const QJsonValue & value, kbdBindings) {
        QJsonObject curr = value.toObject();
        QString tmpStr = "bindsym ";
        if(curr.contains("locked") && curr["locked"].toBool()) {
            tmpStr += "--locked ";
        }
        tmpStr += curr["combi"].toString() + " ";
        tmpStr += curr["type"].toString() + " ";
        tmpStr += curr["clause"].toString() + " \n";
        qInfo() << tmpStr;
        configStr.push_back(tmpStr.toLocal8Bit());
    }
    return configStr;
}

QString Dialog::getKbdShortcut()
{
    QJsonArray kbdArray = kbdConfig.array();
    quint32 currIndex = ui->cmbAction->currentIndex();
    QJsonObject currObj = kbdArray[currIndex].toObject();
    return currObj["combi"].toString();
}

void Dialog::setKbdShortcut(QString combi)
{
    QJsonArray kbdArray = kbdConfig.array();
    quint32 currIndex = ui->cmbAction->currentIndex();
    QJsonObject currObj = kbdArray[currIndex].toObject();
    currObj["combi"] = combi;
    kbdArray[currIndex] = currObj;
    kbdConfig.setArray(kbdArray);
}

void Dialog::on_pbReset_clicked()
{
    qInfo() << "Resetting keybindings to defaults";
    resetDefaults();
}

void Dialog::on_pbSave_clicked()
{
    writeJson();
    QByteArray configGenStr = generateConfig();
    writeConfig(configGenStr);
    emit save();
}

void Dialog::on_pbRecord_clicked()
{
//    ui->ksShortcut->clear();
//    ui->ksShortcut->setFocus(Qt::MouseFocusReason);
}

//void Dialog::saveSequence()
//{
//    qInfo()<<ui->ksShortcut->keySequence();
//}


void Dialog::on_cmbAction_currentIndexChanged(int index)
{
    ui->leShortcut->setText(getKbdShortcut());
}


void Dialog::on_leShortcut_textChanged(const QString &arg1)
{
    QString combi = getKbdShortcut();
    setKbdShortcut(ui->leShortcut->text());
}
